export const UPGRADE_TICK = 'EVOMAP::UPGRADE_TICK';
export const INSERT_ITEM = 'EVOMAP::INSERT_ITEM';
export const HIGHLIGHT_ITEM = 'EVOMAP::HIGHLIGHT_ITEM';
export const SWAP_WALLS = 'EVOMAP::SWAP_WALLS';
